### ISSUE TITLE
python3-tk required to run the python tutorial example

### ISSUE THREAD

**Issue by diregoblin** [multiscale/muscle3#26]
When the example reaction_diffusion.py is executed with python 3.5.3 without python-tk, the following message comes up:

```
Traceback (most recent call last):

  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./reaction_diffusion.py", line 4, in <module>
    from matplotlib import pyplot as plt
  File "/home/asvitenkov/muscle3_venv/lib/python3.5/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/home/asvitenkov/muscle3_venv/lib/python3.5/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/asvitenkov/muscle3_venv/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/home/asvitenkov/muscle3_venv/lib/python3.5/site-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
```

That's an issue with matplotlib, apparently.

**Comment by LourensVeen** [comment]
Actually, the error message already tells the user how to fix this, namely by installing the python3-tk package. And it's a system issue, not a MUSCLE 3 issue.

So I'll just add a note here to say that typing
```sudo apt-get install python3-tk```
on the command line should fix this, in case anyone comes here by searching this error message, and leave the documentation alone.

Alternatively, you can run with plotting disabled as described in the manual, if ``python3-tk`` is missing and you cannot install it.
